Update samples.rst
walmartlabs/lacinia pull request #342
Opened 2020-10-14 18:29 UTC by matteoredaelli

new sample projects

2020-10-14 19:33 UTC, hlship requested changes

2020-10-14 19:33 UTC, hlship commented on docs/samples.rst
> +  A sample library for querying a LDAP/Active directory using GraphQL
`an`

2020-10-14 19:34 UTC, hlship commented
Look like nice, basic services that people can learn from.

2020-10-14 20:07 UTC, matteoredaelli commented
done. not sure if I have to create a new pull request or my last commit (in patch-2 branch) is automatically included in my previous pull request

2020-12-30 21:03 UTC, hlship approved these changes

2020-12-30 21:03 UTC, merged